### ISSUE TITLE
Nothing happens after install

### ISSUE THREAD

**Issue by deejayalbatros** [OCA/oca-decorators#11]
I installed this lib through pip install oca-decorators. Actually I need it for the pos_pricelist module for Odoo. Before installation of this lib I cannot install the pricelist Odoo module, after I also can't. Even though the installation of oca-decorators went successful according to the command line. I've tried a reboot, restarting Odoo server but to no avail...

**Comment by pedrobaeza** [comment]
You shouldn't have installed it properly. Check virtual environments, python 2/3, etc, but it's not a question of the module itself, but a deployment.

**Comment by deejayalbatros** [comment]
What do you mean by you shouldn't have installed it properly Pedro? Can you give me at least some direction where to go...?

**Comment by pedrobaeza** [comment]
Sorry but no with current information, as it totally depends on your environment, how you are installing the module, etc. What I have clear is that this works when the library is available on the Python environment that runs your Odoo.
