### ISSUE TITLE
[RFC] oca.mixins

### ISSUE THREAD

**Issue by hbrunn** [OCA/oca-decorators#4]
seems a good idea to me. We already have some modules adding mixins, they might have a better home in a library. But we'd create a new project for that, right?

I also want to create `GroupableMixin` some time which adds the function `grouped(*fields)` yielding recordsets grouped by the fields given.

**Comment by lasley** [comment]
Yup it would require a new project, probably under the Tools PSC like this one. Fairly simple process assuming we get the votes (mine's in the main issue comment).
