### ISSUE TITLE
Docs not working

### ISSUE THREAD

**Issue by yajo** [OCA/oca-decorators#5]
README points to https://oca.github.io/oca-decorators/ but it's a 404!

cc @lasley

**Comment by lasley** [comment]
Yeah my build system solution was rejected for standardized tools. Seems those tools don't do documentation, but I don't know how to fix it unfortunately. I spent way too many dev hours trying to figure out the standardized systems before I just decided to build my own, and am not willing to go down that same rabbit hole again.

REF https://github.com/OCA/oca-decorators/pull/1#issuecomment-339379340

**Comment by lasley** [comment]
Hey @Yajo - Please see #9
